<?php

return [

    /*
    |--------------------------------------------------------------------------
    | Authentication Defaults
    |--------------------------------------------------------------------------
    |
    | This option controls the default authentication "guard" and password
    | reset options for your application. You may change these defaults
    | as required, but they're a perfect start for most applications.
    |
    */

    // big slider of home
    'single'=>[
        'women'=>[
            'accessory'=>[
                            array(
                                'id'=>'9',
                                'src'=>'/images/women/accessories/acc1.jpg',
                                'title'=>'Hot Sunglasses',
                                'desc'=>'Made in Thailand',
                                'actual_price'=>'$100.00',
                                'discount_price'=>'$70.00',
                                'detail'=>'It is the newest style, it is suitable with teen as well'
                                ),
                            array(
                                'id'=>'10',
                                'src'=>'/images/women/accessories/acc3.jpg',
                                'title'=>'Bracelet Jewellery',
                                'desc'=>'Made in Australia',
                                'actual_price'=>'$70.00',
                                'discount_price'=>'$60.00',
                                'detail'=>'Womens sterling silver bracelet bohemian style faux suede emboss cut out tree bracelet for women stainless steel cz eternity bangle bracelet women 39 s jewelry 107 00.'
                                ),
                            ],
            'bag'=>[
                            array(
                                'id'=>'11',
                                'src'=>'/images/women/bags/b1.jpg',
                                'title'=>'Handbag Women',
                                'desc'=>'Made in US',
                                'actual_price'=>'$123.00',
                                'discount_price'=>'$100.00',
                                'detail'=>'Specifications of Isabel K027 Fringed Sling Bag with Matching Coin Purse'
                                ),
                            array(
                                'id'=>'12',
                                'src'=>'/images/women/bags/b2.jpg',
                                'title'=>'Jewelmine Hammock',
                                'desc'=>'Made in US',
                                'actual_price'=>'$200.00',
                                'discount_price'=>'$190.00',
                                'detail'=>'Specifications of Isabel K027 Fringed Sling Bag with Matching Coin Purse'
                                ),
                            ],
            'hat'=>[
                array(
                    'id'=>'13',
                    'src'=>'/images/women/hats/hat1.jpg',
                    'title'=>'Lady Hat Baseball Caps',
                    'desc'=>'Made in Sydney',
                    'actual_price'=>'$25.00',
                    'discount_price'=>'$15.00',  
                    'detail'=>' Buy Elegant Women Hat Winter & Fall Beanies Knitted Hats For Woman Rabbit Fur Cap Autumn And Winter Ladies Female Fashion Skullies'                  
                    ),
                array(
                    'id'=>'14',
                    'src'=>'/images/women/hats/hat2.jpg',
                    'title'=>'Elegant',
                    'desc'=>'Made in US',
                    'actual_price'=>'$20.00',
                    'discount_price'=>'$10.00', 
                    'detail'=>' Buy Elegant Women Hat Winter & Fall Beanies Knitted Hats For Woman Rabbit Fur Cap Autumn And Winter Ladies Female Fashion Skullies'   
                    ),
                array(
                    'id'=>'15',
                    'src'=>'/images/women/hats/hat3.jpg',
                    'title'=>'Best Cap',
                    'desc'=>'Made in China',
                    'actual_price'=>'$30.00',
                    'discount_price'=>'$20.00',  
                    'detail'=>'2015 Fashion Women Hat Lady Sequin Winter Folds Flat Cap Black Grey Burgundy Cyan blue Beret Caps Visors Hat Octagonal Cap'  
                    ),
                array(
                    'id'=>'16',
                    'src'=>'/images/women/hats/hat4.jpg',
                    'title'=>'Women1',
                    'desc'=>'Sed ut perspiciati1',
                    'actual_price'=>'$70.00',
                    'discount_price'=>'$60.00',    
                    ),
                array(
                    'id'=>'17',
                    'src'=>'/images/women/hats/hat5.jpg',
                    'title'=>'Women1',
                    'desc'=>'Sed ut perspiciati1',
                    'actual_price'=>'$70.00',
                    'discount_price'=>'$60.00',    
                    ),
                array(
                    'id'=>'18',
                    'src'=>'/images/women/hats/hat6.jpg',
                    'title'=>'Women1',
                    'desc'=>'Sed ut perspiciati1',
                    'actual_price'=>'$70.00',
                    'discount_price'=>'$60.00',    
                    ),
                array(
                    'id'=>'19',
                    'src'=>'/images/women/hats/hat7.jpg',
                    'title'=>'Women1',
                    'desc'=>'Sed ut perspiciati1',
                    'actual_price'=>'$70.00',
                    'discount_price'=>'$60.00',    
                    ),
                array(
                    'id'=>'20',
                    'src'=>'/images/women/hats/hat8.jpg',
                    'title'=>'Women1',
                    'desc'=>'Sed ut perspiciati1',
                    'actual_price'=>'$70.00',
                    'discount_price'=>'$60.00',    
                    ),

            ],

            'jacket'=>[
                array(
                    'id'=>'21',
                    'src'=>'/images/women/jacket/j1.jpg',
                    'title'=>'Women1',
                    'desc'=>'Sed ut perspiciati1',
                    'actual_price'=>'$70.00',
                    'discount_price'=>'$60.00',                  
                    ),
                array(
                    'id'=>'22',
                    'src'=>'/images/women/jacket/j2.jpg',
                    'title'=>'Women1',
                    'desc'=>'Sed ut perspiciati1',
                    'actual_price'=>'$70.00',
                    'discount_price'=>'$60.00',    
                    ),
                array(
                    'id'=>'23',
                    'src'=>'/images/women/jacket/j3.jpg',
                    'title'=>'Women1',
                    'desc'=>'Sed ut perspiciati1',
                    'actual_price'=>'$70.00',
                    'discount_price'=>'$60.00',    
                    ),
                array(
                    'id'=>'24',
                    'src'=>'/images/women/jacket/j4.jpg',
                    'title'=>'Women1',
                    'desc'=>'Sed ut perspiciati1',
                    'actual_price'=>'$70.00',
                    'discount_price'=>'$60.00',    
                    ),
                array(
                    'id'=>'25',
                    'src'=>'/images/women/jacket/j5.jpg',
                    'title'=>'Women1',
                    'desc'=>'Sed ut perspiciati1',
                    'actual_price'=>'$70.00',
                    'discount_price'=>'$60.00',    
                    ),
                array(
                    'id'=>'26',
                    'src'=>'/images/women/jacket/j6.jpg',
                    'title'=>'Women1',
                    'desc'=>'Sed ut perspiciati1',
                    'actual_price'=>'$70.00',
                    'discount_price'=>'$60.00',    
                    ),
                array(
                    'id'=>'27',
                    'src'=>'/images/women/jacket/j7.jpg',
                    'title'=>'Women1',
                    'desc'=>'Sed ut perspiciati1',
                    'actual_price'=>'$70.00',
                    'discount_price'=>'$60.00',    
                    ),
                array(
                    'id'=>'28',
                    'src'=>'/images/women/jacket/j8.jpg',
                    'title'=>'Women1',
                    'desc'=>'Sed ut perspiciati1',
                    'actual_price'=>'$70.00',
                    'discount_price'=>'$60.00',    
                    ),

            ],
            'jean'=>[
                array(
                    'id'=>'29',
                    'src'=>'/images/women/jean/jean1.jpg',
                    'title'=>'Women1',
                    'desc'=>'Sed ut perspiciati1',
                    'actual_price'=>'$70.00',
                    'discount_price'=>'$60.00',                    
                    ),
                array(
                    'id'=>'30',
                    'src'=>'/images/women/jean/jean2.jpg',
                    'title'=>'Women1',
                    'desc'=>'Sed ut perspiciati1',
                    'actual_price'=>'$70.00',
                    'discount_price'=>'$60.00',    
                    ),
                array(
                    'id'=>'31',
                    'src'=>'/images/women/jean/jean3.jpg',
                    'title'=>'Women1',
                    'desc'=>'Sed ut perspiciati1',
                    'actual_price'=>'$70.00',
                    'discount_price'=>'$60.00',    
                    ),
                array(
                    'id'=>'32',
                    'src'=>'/images/women/jean/jean4.jpg',
                    'title'=>'Women1',
                    'desc'=>'Sed ut perspiciati1',
                    'actual_price'=>'$70.00',
                    'discount_price'=>'$60.00',    
                    ),
            ],            
            'jewellery'=>[
                array(
                    'id'=>'33',
                    'src'=>'/images/women/jewellery/jew1.jpg',
                    'title'=>'Women1',
                    'desc'=>'Sed ut perspiciati1',
                    'actual_price'=>'$70.00',
                    'discount_price'=>'$60.00',                    
                    ),
                array(
                    'id'=>'34',
                    'src'=>'/images/women/jewellery/jew2.png',
                    'title'=>'Women1',
                    'desc'=>'Sed ut perspiciati1',
                    'actual_price'=>'$70.00',
                    'discount_price'=>'$60.00',    
                    ),
                array(
                    'id'=>'35',
                    'src'=>'/images/women/jewellery/jew3.jpg',
                    'title'=>'Women1',
                    'desc'=>'Sed ut perspiciati1',
                    'actual_price'=>'$70.00',
                    'discount_price'=>'$60.00',    
                    ),
                array(
                    'id'=>'36',
                    'src'=>'/images/women/jewellery/jew4.jpg',
                    'title'=>'Women1',
                    'desc'=>'Sed ut perspiciati1',
                    'actual_price'=>'$70.00',
                    'discount_price'=>'$60.00',    
                    ),
            ],
            'jumper'=>[
                array(
                    'id'=>'37',
                    'src'=>'/images/women/jumper/jum1.jpg',
                    'title'=>'Women1',
                    'desc'=>'Sed ut perspiciati1',
                    'actual_price'=>'$70.00',
                    'discount_price'=>'$60.00',                    
                    ),
                array(
                    'id'=>'38',
                    'src'=>'/images/women/jumper/jum2.jpeg',
                    'title'=>'Women1',
                    'desc'=>'Sed ut perspiciati1',
                    'actual_price'=>'$70.00',
                    'discount_price'=>'$60.00',    
                    ),
                array(
                    'id'=>'39',
                    'src'=>'/images/women/jumper/jum3.jpeg',
                    'title'=>'Women1',
                    'desc'=>'Sed ut perspiciati1',
                    'actual_price'=>'$70.00',
                    'discount_price'=>'$60.00',    
                    ),
                array(
                    'id'=>'40',
                    'src'=>'/images/women/jumper/jum4.jpg',
                    'title'=>'Women1',
                    'desc'=>'Sed ut perspiciati1',
                    'actual_price'=>'$70.00',
                    'discount_price'=>'$60.00',    
                    ),
            ],
            'leatherjacket'=>[
                array(
                    'id'=>'41',
                    'src'=>'/images/women/leatherjacket/l1.jpg',
                    'title'=>'Women1',
                    'desc'=>'Sed ut perspiciati1',
                    'actual_price'=>'$70.00',
                    'discount_price'=>'$60.00',                    
                    ),
                array(
                    'id'=>'42',
                    'src'=>'/images/women/leatherjacket/l2.jpg',
                    'title'=>'Women1',
                    'desc'=>'Sed ut perspiciati1',
                    'actual_price'=>'$70.00',
                    'discount_price'=>'$60.00',    
                    ),
                array(
                    'id'=>'43',
                    'src'=>'/images/women/leatherjacket/l3.jpg',
                    'title'=>'Women1',
                    'desc'=>'Sed ut perspiciati1',
                    'actual_price'=>'$70.00',
                    'discount_price'=>'$60.00',    
                    ),
                array(
                    'id'=>'44',
                    'src'=>'/images/women/leatherjacket/l4.jpg',
                    'title'=>'Women1',
                    'desc'=>'Sed ut perspiciati1',
                    'actual_price'=>'$70.00',
                    'discount_price'=>'$60.00',    
                    ),
                array(
                    'id'=>'45',
                    'src'=>'/images/women/leatherjacket/l5.jpg',
                    'title'=>'Women1',
                    'desc'=>'Sed ut perspiciati1',
                    'actual_price'=>'$70.00',
                    'discount_price'=>'$60.00',    
                    ),            
            ],
            'longsleeve'=>[
                array(
                    'id'=>'46',
                    'src'=>'/images/women/longsleeve/ls1.jpg',
                    'title'=>'Women1',
                    'desc'=>'Sed ut perspiciati1',
                    'actual_price'=>'$70.00',
                    'discount_price'=>'$60.00',                    
                    ),
                array(
                    'id'=>'47',
                    'src'=>'/images/women/longsleeve/ls2.jpg',
                    'title'=>'Women1',
                    'desc'=>'Sed ut perspiciati1',
                    'actual_price'=>'$70.00',
                    'discount_price'=>'$60.00',    
                    ),
                array(
                    'id'=>'48',
                    'src'=>'/images/women/longsleeve/ls3.jpg',
                    'title'=>'Women1',
                    'desc'=>'Sed ut perspiciati1',
                    'actual_price'=>'$70.00',
                    'discount_price'=>'$60.00',    
                    ),
                array(
                    'id'=>'49',
                    'src'=>'/images/women/longsleeve/ls4.jpg',
                    'title'=>'Women1',
                    'desc'=>'Sed ut perspiciati1',
                    'actual_price'=>'$70.00',
                    'discount_price'=>'$60.00',    
                    ),
            ],
            'shirt'=>[
                array(
                    'id'=>'50',
                    'src'=>'/images/women/shirt/shirt1.jpg',
                    'title'=>'Women1',
                    'desc'=>'Sed ut perspiciati1',
                    'actual_price'=>'$70.00',
                    'discount_price'=>'$60.00',                    
                    ),
                array(
                    'id'=>'51',
                    'src'=>'/images/women/shirt/shirt2.jpg',
                    'title'=>'Women1',
                    'desc'=>'Sed ut perspiciati1',
                    'actual_price'=>'$70.00',
                    'discount_price'=>'$60.00',     
                    ),
                array(
                    'id'=>'52',
                    'src'=>'/images/women/shirt/shirt3.jpg',
                    'title'=>'Women1',
                    'desc'=>'Sed ut perspiciati1',
                    'actual_price'=>'$70.00',
                    'discount_price'=>'$60.00',    
                    ),
                array(
                    'id'=>'53',
                    'src'=>'/images/women/shirt/shirt4.jpg',
                    'title'=>'Women1',
                    'desc'=>'Sed ut perspiciati1',
                    'actual_price'=>'$70.00',
                    'discount_price'=>'$60.00',    
                    ),
                array(
                    'id'=>'200',
                    'src'=>'/images/pc.jpg',
                    'title'=>'Women1',
                    'desc'=>'Sed ut perspiciati1',
                    'actual_price'=>'$70.00',
                    'discount_price'=>'$60.00',    
                    'trending_item'=>true,  
                    ),
                array(
                    'id'=>'201',
                    'src'=>'/images/pc1.jpg',
                    'title'=>'Women1',
                    'desc'=>'Sed ut perspiciati1',
                    'actual_price'=>'$70.00',
                    'discount_price'=>'$60.00',    
                    'trending_item'=>true,  
                    ),
                array(
                    'id'=>'202',
                    'src'=>'/images/pc2.jpg',
                    'title'=>'Women1',
                    'desc'=>'Sed ut perspiciati1',
                    'actual_price'=>'$70.00',
                    'discount_price'=>'$60.00',    
                    'trending_item'=>true,  
                    ),
                array(
                    'id'=>'203',
                    'src'=>'/images/pc3.jpg',
                    'title'=>'Women1',
                    'desc'=>'Sed ut perspiciati1',
                    'actual_price'=>'$70.00',
                    'discount_price'=>'$60.00',    
                    'trending_item'=>true,  
                    ),
                array(
                    'id'=>'204',
                    'src'=>'/images/pc4.jpg',
                    'title'=>'Women1',
                    'desc'=>'Sed ut perspiciati1',
                    'actual_price'=>'$70.00',
                    'discount_price'=>'$60.00',    
                    'trending_item'=>true,  
                    ),
                array(
                    'id'=>'205',
                    'src'=>'/images/pc5.jpg',
                    'title'=>'Women1',
                    'desc'=>'Sed ut perspiciati1',
                    'actual_price'=>'$70.00',
                    'discount_price'=>'$60.00',    
                    'trending_item'=>true,  
                    ),
                array(
                    'id'=>'206',
                    'src'=>'/images/pc6.jpg',
                    'title'=>'Women1',
                    'desc'=>'Sed ut perspiciati1',
                    'actual_price'=>'$70.00',
                    'discount_price'=>'$60.00',    
                    'trending_item'=>true,  
                    ),
                array(
                    'id'=>'207',
                    'src'=>'/images/pc7.jpg',
                    'title'=>'Women1',
                    'desc'=>'Sed ut perspiciati1',
                    'actual_price'=>'$70.00',
                    'discount_price'=>'$60.00',    
                    'trending_item'=>true,  
                    ),                
            ],
            'shoes'=>[
                array(
                    'id'=>'54',
                    'src'=>'/images/women/shoes/shoes1.jpg',
                    'title'=>'Women1',
                    'desc'=>'Sed ut perspiciati1',
                    'actual_price'=>'$70.00',
                    'discount_price'=>'$60.00',                    
                    ),
                array(
                    'id'=>'55',
                    'src'=>'/images/women/shoes/shoes2.jpg',
                    'title'=>'Women1',
                    'desc'=>'Sed ut perspiciati1',
                    'actual_price'=>'$70.00',
                    'discount_price'=>'$60.00',    
                    ),
                array(
                    'id'=>'56',
                    'src'=>'/images/women/shoes/shoes3.jpg',
                    'title'=>'Women1',
                    'desc'=>'Sed ut perspiciati1',
                    'actual_price'=>'$70.00',
                    'discount_price'=>'$60.00',    
                    ),
                array(
                    'id'=>'57',
                    'src'=>'/images/women/shoes/shoes4.jpg',
                    'title'=>'Women1',
                    'desc'=>'Sed ut perspiciati1',
                    'actual_price'=>'$70.00',
                    'discount_price'=>'$60.00',    
                    ),
                array(
                    'id'=>'58',
                    'src'=>'/images/women/shoes/shoes5.jpg',
                    'title'=>'Women1',
                    'desc'=>'Sed ut perspiciati1',
                    'actual_price'=>'$70.00',
                    'discount_price'=>'$60.00',    
                    ),
                array(
                    'id'=>'59',
                    'src'=>'/images/women/shoes/shoes6.jpg',
                    'title'=>'Women1',
                    'desc'=>'Sed ut perspiciati1',
                    'actual_price'=>'$70.00',
                    'discount_price'=>'$60.00',    
                    ),                
            ],
            'sunglasses'=>[
                array(
                    'id'=>'60',
                    'src'=>'/images/women/sunglasses/glass1.jpg',
                    'title'=>'Women1',
                    'desc'=>'Sed ut perspiciati1',
                    'actual_price'=>'$70.00',
                    'discount_price'=>'$60.00',                    
                    ),
                array(
                    'id'=>'61',
                    'src'=>'/images/women/sunglasses/glass2.jpg',
                    'title'=>'Women1',
                    'desc'=>'Sed ut perspiciati1',
                    'actual_price'=>'$70.00',
                    'discount_price'=>'$60.00',    
                    ),
                array(
                    'id'=>'62',
                    'src'=>'/images/women/sunglasses/glass3.jpg',
                    'title'=>'Women1',
                    'desc'=>'Sed ut perspiciati1',
                    'actual_price'=>'$70.00',
                    'discount_price'=>'$60.00',    
                    ),
                array(
                    'id'=>'63',
                    'src'=>'/images/women/sunglasses/glass4.jpg',
                    'title'=>'Women1',
                    'desc'=>'Sed ut perspiciati1',
                    'actual_price'=>'$70.00',
                    'discount_price'=>'$60.00',    
                    ),
                array(
                    'id'=>'64',
                    'src'=>'/images/women/sunglasses/glass5.jpg',
                    'title'=>'Women1',
                    'desc'=>'Sed ut perspiciati1',
                    'actual_price'=>'$70.00',
                    'discount_price'=>'$60.00',    
                    ),
                array(
                    'id'=>'65',
                    'src'=>'/images/women/sunglasses/glass6.jpg',
                    'title'=>'Women1',
                    'desc'=>'Sed ut perspiciati1',
                    'actual_price'=>'$70.00',
                    'discount_price'=>'$60.00',    
                    ), 
            ],
            'sweatpants'=>[
                array(
                    'id'=>'66',
                    'src'=>'/images/women/sweatpants/sweat1.jpg',
                    'title'=>'Women1',
                    'desc'=>'Sed ut perspiciati1',
                    'actual_price'=>'$70.00',
                    'discount_price'=>'$60.00',                    
                    ),
                array(
                    'id'=>'67',
                    'src'=>'/images/women/sweatpants/sweat2.jpg',
                    'title'=>'Women1',
                    'desc'=>'Sed ut perspiciati1',
                    'actual_price'=>'$70.00',
                    'discount_price'=>'$60.00',    
                    ),
                array(
                    'id'=>'68',
                    'src'=>'/images/women/sweatpants/sweat3.jpg',
                    'title'=>'Women1',
                    'desc'=>'Sed ut perspiciati1',
                    'actual_price'=>'$70.00',
                    'discount_price'=>'$60.00',    
                    ),
                array(
                    'id'=>'69',
                    'src'=>'/images/women/sweatpants/sweat4.jpg',
                    'title'=>'Women1',
                    'desc'=>'Sed ut perspiciati1',
                    'actual_price'=>'$70.00',
                    'discount_price'=>'$60.00',    
                    ),
            ],
            'sweatshirt'=>[
                array(
                    'id'=>'70',
                    'src'=>'/images/women/sweatshirt/s1.jpg',
                    'title'=>'Women1',
                    'desc'=>'Sed ut perspiciati1',
                    'actual_price'=>'$70.00',
                    'discount_price'=>'$60.00',                    
                    ),
                array(
                    'id'=>'71',
                    'src'=>'/images/women/sweatshirt/s2.jpg',
                    'title'=>'Women1',
                    'desc'=>'Sed ut perspiciati1',
                    'actual_price'=>'$70.00',
                    'discount_price'=>'$60.00',    
                    ),
                array(
                    'id'=>'72',
                    'src'=>'/images/women/sweatshirt/s3.jpg',
                    'title'=>'Women1',
                    'desc'=>'Sed ut perspiciati1',
                    'actual_price'=>'$70.00',
                    'discount_price'=>'$60.00',    
                    ),
                array(
                    'id'=>'73',
                    'src'=>'/images/women/sweatshirt/s4.jpg',
                    'title'=>'Women1',
                    'desc'=>'Sed ut perspiciati1',
                    'actual_price'=>'$70.00',
                    'discount_price'=>'$60.00',    
                    ),
                array(
                    'id'=>'74',
                    'src'=>'/images/women/sweatshirt/s5.jpg',
                    'title'=>'Women1',
                    'desc'=>'Sed ut perspiciati1',
                    'actual_price'=>'$70.00',
                    'discount_price'=>'$60.00',                    
                    ),
                array(
                    'id'=>'75',
                    'src'=>'/images/women/sweatshirt/s6.jpg',
                    'title'=>'Women1',
                    'desc'=>'Sed ut perspiciati1',
                    'actual_price'=>'$70.00',
                    'discount_price'=>'$60.00',    
                    ),
                array(
                    'id'=>'76',
                    'src'=>'/images/women/sweatshirt/s7.jpg',
                    'title'=>'Women1',
                    'desc'=>'Sed ut perspiciati1',
                    'actual_price'=>'$70.00',
                    'discount_price'=>'$60.00',    
                    ),
                array(
                    'id'=>'77',
                    'src'=>'/images/women/sweatshirt/s8.jpg',
                    'title'=>'Women1',
                    'desc'=>'Sed ut perspiciati1',
                    'actual_price'=>'$70.00',
                    'discount_price'=>'$60.00',    
                    ),            
            ],
            'swimwear'=>[
                array(
                    'id'=>'78',
                    'src'=>'/images/women/swimwear/swim1.jpg',
                    'title'=>'Women1',
                    'desc'=>'Sed ut perspiciati1',
                    'actual_price'=>'$70.00',
                    'discount_price'=>'$60.00',                    
                    ),
                array(
                    'id'=>'79',
                    'src'=>'/images/women/swimwear/swim2.jpg',
                    'title'=>'Women1',
                    'desc'=>'Sed ut perspiciati1',
                    'actual_price'=>'$70.00',
                    'discount_price'=>'$60.00',    
                    ),
                array(
                    'id'=>'80',
                    'src'=>'/images/women/swimwear/swim3.jpg',
                    'title'=>'Women1',
                    'desc'=>'Sed ut perspiciati1',
                    'actual_price'=>'$70.00',
                    'discount_price'=>'$60.00',    
                    ),
                array(
                    'id'=>'81',
                    'src'=>'/images/women/swimwear/swim4.jpg',
                    'title'=>'Women1',
                    'desc'=>'Sed ut perspiciati1',
                    'actual_price'=>'$70.00',
                    'discount_price'=>'$60.00',    
                    ),
            ],
            'trouser'=>[
                array(
                    'id'=>'82',
                    'src'=>'/images/women/trouser/trouser1.jpg',
                    'title'=>'Women1',
                    'desc'=>'Sed ut perspiciati1',
                    'actual_price'=>'$70.00',
                    'discount_price'=>'$60.00',                    
                    ),
                array(
                    'id'=>'83',
                    'src'=>'/images/women/trouser/trouser2.jpg',
                    'title'=>'Women1',
                    'desc'=>'Sed ut perspiciati1',
                    'actual_price'=>'$70.00',
                    'discount_price'=>'$60.00',    
                    ),
                array(
                    'id'=>'84',
                    'src'=>'/images/women/trouser/trouser3.jpg',
                    'title'=>'Women1',
                    'desc'=>'Sed ut perspiciati1',
                    'actual_price'=>'$70.00',
                    'discount_price'=>'$60.00',    
                    ),
                array(
                    'id'=>'85',
                    'src'=>'/images/women/trouser/trouser4.jpg',
                    'title'=>'Women1',
                    'desc'=>'Sed ut perspiciati1',
                    'actual_price'=>'$70.00',
                    'discount_price'=>'$60.00',    
                    ),
            ],
            'tshirt'=>[
                array(
                    'id'=>'86',
                    'src'=>'/images/women/tshirt/t1.jpg',
                    'title'=>'Women1',
                    'desc'=>'Sed ut perspiciati1',
                    'actual_price'=>'$70.00',
                    'discount_price'=>'$60.00',                    
                    ),
                array(
                    'id'=>'87',
                    'src'=>'/images/women/tshirt/t2.jpg',
                    'title'=>'Women1',
                    'desc'=>'Sed ut perspiciati1',
                    'actual_price'=>'$70.00',
                    'discount_price'=>'$60.00',    
                    ),
                array(
                    'id'=>'88',
                    'src'=>'/images/women/tshirt/t3.jpg',
                    'title'=>'Women1',
                    'desc'=>'Sed ut perspiciati1',
                    'actual_price'=>'$70.00',
                    'discount_price'=>'$60.00',    
                    ),
                array(
                    'id'=>'89',
                    'src'=>'/images/women/tshirt/t4.jpg',
                    'title'=>'Women1',
                    'desc'=>'Sed ut perspiciati1',
                    'actual_price'=>'$70.00',
                    'discount_price'=>'$60.00',    
                    ),
                array(
                    'id'=>'90',
                    'src'=>'/images/women/tshirt/t5.jpg',
                    'title'=>'Women1',
                    'desc'=>'Sed ut perspiciati1',
                    'actual_price'=>'$70.00',
                    'discount_price'=>'$60.00',                    
                    ),
                array(
                    'id'=>'91',
                    'src'=>'/images/women/tshirt/t6.jpg',
                    'title'=>'Women1',
                    'desc'=>'Sed ut perspiciati1',
                    'actual_price'=>'$70.00',
                    'discount_price'=>'$60.00',    
                    ),
                array(
                    'id'=>'92',
                    'src'=>'/images/women/tshirt/t7.jpg',
                    'title'=>'Women1',
                    'desc'=>'Sed ut perspiciati1',
                    'actual_price'=>'$70.00',
                    'discount_price'=>'$60.00',    
                    ),
                array(
                    'id'=>'93',
                    'src'=>'/images/women/tshirt/t8.jpg',
                    'title'=>'Women1',
                    'desc'=>'Sed ut perspiciati1',
                    'actual_price'=>'$70.00',
                    'discount_price'=>'$60.00',    
                    ),                
            ],
            'underwear'=>[
                array(
                    'id'=>'94',
                    'src'=>'/images/women/underwear/u1.jpg',
                    'title'=>'Women1',
                    'desc'=>'Sed ut perspiciati1',
                    'actual_price'=>'$70.00',
                    'discount_price'=>'$60.00',                    
                    ),
                array(
                    'id'=>'95',
                    'src'=>'/images/women/underwear/u2.jpg',
                    'title'=>'Women1',
                    'desc'=>'Sed ut perspiciati1',
                    'actual_price'=>'$70.00',
                    'discount_price'=>'$60.00',    
                    ),
                array(
                    'id'=>'96',
                    'src'=>'/images/women/underwear/u3.jpg',
                    'title'=>'Women1',
                    'desc'=>'Sed ut perspiciati1',
                    'actual_price'=>'$70.00',
                    'discount_price'=>'$60.00',    
                    ),
                array(
                    'id'=>'97',
                    'src'=>'/images/women/underwear/u4.jpg',
                    'title'=>'Women1',
                    'desc'=>'Sed ut perspiciati1',
                    'actual_price'=>'$70.00',
                    'discount_price'=>'$60.00',    
                    ),
            ],
            'vest'=>[
                array(
                    'id'=>'98',
                    'src'=>'/images/women/vest/v1.jpg',
                    'title'=>'Women1',
                    'desc'=>'Sed ut perspiciati1',
                    'actual_price'=>'$70.00',
                    'discount_price'=>'$60.00',                    
                    ),
                array(
                    'id'=>'99',
                    'src'=>'/images/women/vest/v2.jpg',
                    'title'=>'Women1',
                    'desc'=>'Sed ut perspiciati1',
                    'actual_price'=>'$70.00',
                    'discount_price'=>'$60.00',    
                    ),
                array(
                    'id'=>'100',
                    'src'=>'/images/women/vest/v3.jpg',
                    'title'=>'Women1',
                    'desc'=>'Sed ut perspiciati1',
                    'actual_price'=>'$70.00',
                    'discount_price'=>'$60.00',    
                    ),
                array(
                    'id'=>'101',
                    'src'=>'/images/women/vest/v4.jpg',
                    'title'=>'Women1',
                    'desc'=>'Sed ut perspiciati1',
                    'actual_price'=>'$70.00',
                    'discount_price'=>'$60.00',    
                    ),
            ],          
                ],
        'men'=>[
            'accessory'=>[
                    array(
                        'id'=>'102',
                        'src'=>'/images/men/accessories/acc1.jpg',
                        'title'=>'men',
                        'desc'=>'Sed ut perspiciati',
                        'actual_price'=>'$100.00',
                        'discount_price'=>'$70.00',
                        ),
                    array(
                        'id'=>'103',
                        'src'=>'/images/men/accessories/acc2.jpg',
                        'title'=>'men1',
                        'desc'=>'Sed ut perspiciati1',
                        'actual_price'=>'$70.00',
                        'discount_price'=>'$60.00',
                        ),
                    ],
            'bag'=>[
                    array(
                        'id'=>'104',
                        'src'=>'/images/men/bags/b1.jpg',
                        'title'=>'men',
                        'desc'=>'Sed ut perspiciati',
                        'actual_price'=>'$100.00',
                        'discount_price'=>'$70.00',
                        ),
                    array(
                        'id'=>'105',
                        'src'=>'/images/men/bags/b2.jpg',
                        'title'=>'men1',
                        'desc'=>'Sed ut perspiciati1',
                        'actual_price'=>'$70.00',
                        'discount_price'=>'$60.00',
                        ),
                    array(
                        'id'=>'106',
                        'src'=>'/images/men/bags/b3.jpg',
                        'title'=>'men',
                        'desc'=>'Sed ut perspiciati',
                        'actual_price'=>'$100.00',
                        'discount_price'=>'$70.00',
                        ),
                    array(
                        'id'=>'107',
                        'src'=>'/images/men/bags/b4.jpg',
                        'title'=>'men1',
                        'desc'=>'Sed ut perspiciati1',
                        'actual_price'=>'$70.00',
                        'discount_price'=>'$60.00',
                        ),      
                    array(
                        'id'=>'108',
                        'src'=>'/images/men/bags/b5.jpg',
                        'title'=>'men',
                        'desc'=>'Sed ut perspiciati',
                        'actual_price'=>'$100.00',
                        'discount_price'=>'$70.00',
                        ),
                    array(
                        'id'=>'109',
                        'src'=>'/images/men/bags/b6.jpg',
                        'title'=>'men1',
                        'desc'=>'Sed ut perspiciati1',
                        'actual_price'=>'$70.00',
                        'discount_price'=>'$60.00',
                        ),
                    array(
                        'id'=>'110',
                        'src'=>'/images/men/bags/b7.jpg',
                        'title'=>'men',
                        'desc'=>'Sed ut perspiciati',
                        'actual_price'=>'$100.00',
                        'discount_price'=>'$70.00',
                        ),
                    array(
                        'id'=>'111',
                        'src'=>'/images/men/bags/b8.jpg',
                        'title'=>'men1',
                        'desc'=>'Sed ut perspiciati1',
                        'actual_price'=>'$70.00',
                        'discount_price'=>'$60.00',
                        ),                                        
                    ],
            'hat'=>[
                array(
                    'id'=>'112',
                    'src'=>'/images/men/hats/hat1.jpg',
                    'title'=>'men1',
                    'desc'=>'Sed ut perspiciati1',
                    'actual_price'=>'$70.00',
                    'discount_price'=>'$60.00',                    
                    ),
                array(
                    'id'=>'113',
                    'src'=>'/images/men/hats/hat2.jpg',
                    'title'=>'men1',
                    'desc'=>'Sed ut perspiciati1',
                    'actual_price'=>'$70.00',
                    'discount_price'=>'$60.00',    
                    ),
                array(
                    'id'=>'114',
                    'src'=>'/images/men/hats/hat3.jpg',
                    'title'=>'men1',
                    'desc'=>'Sed ut perspiciati1',
                    'actual_price'=>'$70.00',
                    'discount_price'=>'$60.00',    
                    ),
                array(
                    'id'=>'115',
                    'src'=>'/images/men/hats/hat4.jpg',
                    'title'=>'men1',
                    'desc'=>'Sed ut perspiciati1',
                    'actual_price'=>'$70.00',
                    'discount_price'=>'$60.00',    
                    ),
                array(
                    'id'=>'116',
                    'src'=>'/images/men/hats/hat7.jpg',
                    'title'=>'men1',
                    'desc'=>'Sed ut perspiciati1',
                    'actual_price'=>'$70.00',
                    'discount_price'=>'$60.00',    
                    ),
                array(
                    'id'=>'117',
                    'src'=>'/images/men/hats/hat8.jpg',
                    'title'=>'men1',
                    'desc'=>'Sed ut perspiciati1',
                    'actual_price'=>'$70.00',
                    'discount_price'=>'$60.00',    
                    ),
                array(
                    'id'=>'118',
                    'src'=>'/images/men/hats/hat5.jpg',
                    'title'=>'men1',
                    'desc'=>'Sed ut perspiciati1',
                    'actual_price'=>'$70.00',
                    'discount_price'=>'$60.00',    
                    ),
                array(
                    'id'=>'119',
                    'src'=>'/images/men/hats/hat6.jpg',
                    'title'=>'men1',
                    'desc'=>'Sed ut perspiciati1',
                    'actual_price'=>'$70.00',
                    'discount_price'=>'$60.00',    
                    ),                

            ],

            'jacket'=>[
                array(
                    'id'=>'120',
                    'src'=>'/images/men/jacket/j1.jpg',
                    'title'=>'men1',
                    'desc'=>'Sed ut perspiciati1',
                    'actual_price'=>'$70.00',
                    'discount_price'=>'$60.00',                    
                    ),
                array(
                    'id'=>'121',
                    'src'=>'/images/men/jacket/j2.jpg',
                    'title'=>'men1',
                    'desc'=>'Sed ut perspiciati1',
                    'actual_price'=>'$70.00',
                    'discount_price'=>'$60.00',    
                    ),
                array(
                    'id'=>'122',
                    'src'=>'/images/men/jacket/j3.jpg',
                    'title'=>'men1',
                    'desc'=>'Sed ut perspiciati1',
                    'actual_price'=>'$70.00',
                    'discount_price'=>'$60.00',    
                    ),
                array(
                    'id'=>'123',
                    'src'=>'/images/men/jacket/j4.jpg',
                    'title'=>'men1',
                    'desc'=>'Sed ut perspiciati1',
                    'actual_price'=>'$70.00',
                    'discount_price'=>'$60.00',    
                    ),
                array(
                    'id'=>'124',
                    'src'=>'/images/men/jacket/j5.jpg',
                    'title'=>'men1',
                    'desc'=>'Sed ut perspiciati1',
                    'actual_price'=>'$70.00',
                    'discount_price'=>'$60.00',    
                    ),
                array(
                    'id'=>'125',
                    'src'=>'/images/men/jacket/j6.jpg',
                    'title'=>'men1',
                    'desc'=>'Sed ut perspiciati1',
                    'actual_price'=>'$70.00',
                    'discount_price'=>'$60.00',    
                    ),
                array(
                    'id'=>'126',
                    'src'=>'/images/men/jacket/j7.jpg',
                    'title'=>'men1',
                    'desc'=>'Sed ut perspiciati1',
                    'actual_price'=>'$70.00',
                    'discount_price'=>'$60.00',    
                    ),
                array(
                    'id'=>'127',
                    'src'=>'/images/men/jacket/j8.jpg',
                    'title'=>'men1',
                    'desc'=>'Sed ut perspiciati1',
                    'actual_price'=>'$70.00',
                    'discount_price'=>'$60.00',    
                    ),

            ],
            'jean'=>[
                array(
                    'id'=>'128',
                    'src'=>'/images/men/jean/jean1.jpg',
                    'title'=>'men1',
                    'desc'=>'Sed ut perspiciati1',
                    'actual_price'=>'$70.00',
                    'discount_price'=>'$60.00',                    
                    ),
                array(
                    'id'=>'129',
                    'src'=>'/images/men/jean/jean2.jpg',
                    'title'=>'men1',
                    'desc'=>'Sed ut perspiciati1',
                    'actual_price'=>'$70.00',
                    'discount_price'=>'$60.00',    
                    ),
                array(
                    'id'=>'130',
                    'src'=>'/images/men/jean/jean3.jpg',
                    'title'=>'men1',
                    'desc'=>'Sed ut perspiciati1',
                    'actual_price'=>'$70.00',
                    'discount_price'=>'$60.00',    
                    ),
                array(
                    'id'=>'131',
                    'src'=>'/images/men/jean/jean4.jpg',
                    'title'=>'men1',
                    'desc'=>'Sed ut perspiciati1',
                    'actual_price'=>'$70.00',
                    'discount_price'=>'$60.00',    
                    ),
            ],            
            'jewellery'=>[
                array(
                    'id'=>'132',
                    'src'=>'/images/men/jewellery/jew1.jpg',
                    'title'=>'men1',
                    'desc'=>'Sed ut perspiciati1',
                    'actual_price'=>'$70.00',
                    'discount_price'=>'$60.00',                    
                    ),
                array(
                    'id'=>'133',
                    'src'=>'/images/men/jewellery/jew3.jpg',
                    'title'=>'men1',
                    'desc'=>'Sed ut perspiciati1',
                    'actual_price'=>'$70.00',
                    'discount_price'=>'$60.00',    
                    ),
                array(
                    'id'=>'134',
                    'src'=>'/images/men/jewellery/jew4.jpg',
                    'title'=>'men1',
                    'desc'=>'Sed ut perspiciati1',
                    'actual_price'=>'$70.00',
                    'discount_price'=>'$60.00',    
                    ),
            ],
            'jumper'=>[
                array(
                    'id'=>'135',
                    'src'=>'/images/men/jumper/jum1.jpg',
                    'title'=>'men1',
                    'desc'=>'Sed ut perspiciati1',
                    'actual_price'=>'$70.00',
                    'discount_price'=>'$60.00',                    
                    ),
                array(
                    'id'=>'136',
                    'src'=>'/images/men/jumper/jum2.jpeg',
                    'title'=>'men1',
                    'desc'=>'Sed ut perspiciati1',
                    'actual_price'=>'$70.00',
                    'discount_price'=>'$60.00',    
                    ),
                array(
                    'id'=>'137',
                    'src'=>'/images/men/jumper/jum3.jpeg',
                    'title'=>'men1',
                    'desc'=>'Sed ut perspiciati1',
                    'actual_price'=>'$70.00',
                    'discount_price'=>'$60.00',    
                    ),
                array(
                    'id'=>'138',
                    'src'=>'/images/men/jumper/jum4.jpeg',
                    'title'=>'men1',
                    'desc'=>'Sed ut perspiciati1',
                    'actual_price'=>'$70.00',
                    'discount_price'=>'$60.00',    
                    ),
            ],
            'leatherjacket'=>[
                array(
                    'id'=>'139',
                    'src'=>'/images/men/leatherjacket/l1.jpg',
                    'title'=>'men1',
                    'desc'=>'Sed ut perspiciati1',
                    'actual_price'=>'$70.00',
                    'discount_price'=>'$60.00',                    
                    ),
                array(
                    'id'=>'140',
                    'src'=>'/images/men/leatherjacket/l2.jpg',
                    'title'=>'men1',
                    'desc'=>'Sed ut perspiciati1',
                    'actual_price'=>'$70.00',
                    'discount_price'=>'$60.00',    
                    ),
                array(
                    'id'=>'141',
                    'src'=>'/images/men/leatherjacket/l3.jpg',
                    'title'=>'men1',
                    'desc'=>'Sed ut perspiciati1',
                    'actual_price'=>'$70.00',
                    'discount_price'=>'$60.00',    
                    ),
                array(
                    'id'=>'142',
                    'src'=>'/images/men/leatherjacket/l4.jpg',
                    'title'=>'men1',
                    'desc'=>'Sed ut perspiciati1',
                    'actual_price'=>'$70.00',
                    'discount_price'=>'$60.00',    
                    ),
                array(
                    'id'=>'143',
                    'src'=>'/images/men/leatherjacket/l5.jpg',
                    'title'=>'men1',
                    'desc'=>'Sed ut perspiciati1',
                    'actual_price'=>'$70.00',
                    'discount_price'=>'$60.00',    
                    ),            
            ],
            'longsleeve'=>[
                array(
                    'id'=>'144',
                    'src'=>'/images/men/longsleeve/ls1.jpg',
                    'title'=>'men1',
                    'desc'=>'Sed ut perspiciati1',
                    'actual_price'=>'$70.00',
                    'discount_price'=>'$60.00',                    
                    ),
                array(
                    'id'=>'145',
                    'src'=>'/images/men/longsleeve/ls2.jpg',
                    'title'=>'men1',
                    'desc'=>'Sed ut perspiciati1',
                    'actual_price'=>'$70.00',
                    'discount_price'=>'$60.00',    
                    ),
                array(
                    'id'=>'146',
                    'src'=>'/images/men/longsleeve/ls3.jpg',
                    'title'=>'men1',
                    'desc'=>'Sed ut perspiciati1',
                    'actual_price'=>'$70.00',
                    'discount_price'=>'$60.00',    
                    ),
                array(
                    'id'=>'147',
                    'src'=>'/images/men/longsleeve/ls4.png',
                    'title'=>'men1',
                    'desc'=>'Sed ut perspiciati1',
                    'actual_price'=>'$70.00',
                    'discount_price'=>'$60.00',    
                    ),
            ],
            'shirt'=>[
                array(
                    'id'=>'148',
                    'src'=>'/images/men/shirt/shirt1.jpg',
                    'title'=>'men1',
                    'desc'=>'Sed ut perspiciati1',
                    'actual_price'=>'$70.00',
                    'discount_price'=>'$60.00',                    
                    ),
                array(
                    'id'=>'149',
                    'src'=>'/images/men/shirt/shirt2.jpg',
                    'title'=>'men1',
                    'desc'=>'Sed ut perspiciati1',
                    'actual_price'=>'$70.00',
                    'discount_price'=>'$60.00',    
                    ),
                array(
                    'id'=>'150',
                    'src'=>'/images/men/shirt/shirt3.jpg',
                    'title'=>'men1',
                    'desc'=>'Sed ut perspiciati1',
                    'actual_price'=>'$70.00',
                    'discount_price'=>'$60.00',    
                    ),
                array(
                    'id'=>'151',
                    'src'=>'/images/men/shirt/shirt4.jpg',
                    'title'=>'men1',
                    'desc'=>'Sed ut perspiciati1',
                    'actual_price'=>'$70.00',
                    'discount_price'=>'$60.00',    
                    ),
            ],
            'shoes'=>[
                array(
                    'id'=>'152',
                    'src'=>'/images/men/shoes/shoes1.jpg',
                    'title'=>'men1',
                    'desc'=>'Sed ut perspiciati1',
                    'actual_price'=>'$70.00',
                    'discount_price'=>'$60.00',                    
                    ),
                array(
                    'id'=>'153',
                    'src'=>'/images/men/shoes/shoes5.jpg',
                    'title'=>'men1',
                    'desc'=>'Sed ut perspiciati1',
                    'actual_price'=>'$70.00',
                    'discount_price'=>'$60.00',    
                    ),                
                array(
                    'id'=>'154',
                    'src'=>'/images/men/shoes/shoes3.jpg',
                    'title'=>'men1',
                    'desc'=>'Sed ut perspiciati1',
                    'actual_price'=>'$70.00',
                    'discount_price'=>'$60.00',    
                    ),                                
            ],
            'sunglasses'=>[
                array(
                    'id'=>'155',
                    'src'=>'/images/men/sunglasses/glass1.jpg',
                    'title'=>'men1',
                    'desc'=>'Sed ut perspiciati1',
                    'actual_price'=>'$70.00',
                    'discount_price'=>'$60.00',                    
                    ),
                array(
                    'id'=>'156',
                    'src'=>'/images/men/sunglasses/glass2.jpg',
                    'title'=>'men1',
                    'desc'=>'Sed ut perspiciati1',
                    'actual_price'=>'$70.00',
                    'discount_price'=>'$60.00',    
                    ),
                array(
                    'id'=>'157',
                    'src'=>'/images/men/sunglasses/glass3.jpg',
                    'title'=>'men1',
                    'desc'=>'Sed ut perspiciati1',
                    'actual_price'=>'$70.00',
                    'discount_price'=>'$60.00',    
                    ),
                array(
                    'id'=>'158',
                    'src'=>'/images/men/sunglasses/glass4.jpg',
                    'title'=>'men1',
                    'desc'=>'Sed ut perspiciati1',
                    'actual_price'=>'$70.00',
                    'discount_price'=>'$60.00',    
                    ),
                array(
                    'id'=>'159',
                    'src'=>'/images/men/sunglasses/glass5.jpg',
                    'title'=>'men1',
                    'desc'=>'Sed ut perspiciati1',
                    'actual_price'=>'$70.00',
                    'discount_price'=>'$60.00',    
                    ),
                array(
                    'id'=>'160',
                    'src'=>'/images/men/sunglasses/glass6.jpg',
                    'title'=>'men1',
                    'desc'=>'Sed ut perspiciati1',
                    'actual_price'=>'$70.00',
                    'discount_price'=>'$60.00',    
                    ), 
            ],
            'sweatpants'=>[
                array(
                    'id'=>'161',
                    'src'=>'/images/men/sweatpants/sweat1.jpg',
                    'title'=>'men1',
                    'desc'=>'Sed ut perspiciati1',
                    'actual_price'=>'$70.00',
                    'discount_price'=>'$60.00',                    
                    ),
                array(
                    'id'=>'162',
                    'src'=>'/images/men/sweatpants/sweat2.jpg',
                    'title'=>'men1',
                    'desc'=>'Sed ut perspiciati1',
                    'actual_price'=>'$70.00',
                    'discount_price'=>'$60.00',    
                    ),
                array(
                    'id'=>'163',
                    'src'=>'/images/men/sweatpants/sweat3.jpg',
                    'title'=>'men1',
                    'desc'=>'Sed ut perspiciati1',
                    'actual_price'=>'$70.00',
                    'discount_price'=>'$60.00',    
                    ),
                array(
                    'id'=>'164',
                    'src'=>'/images/men/sweatpants/sweat4.jpg',
                    'title'=>'men1',
                    'desc'=>'Sed ut perspiciati1',
                    'actual_price'=>'$70.00',
                    'discount_price'=>'$60.00',    
                    ),
            ],
            'sweatshirt'=>[
                array(
                    'id'=>'165',
                    'src'=>'/images/men/sweatshirt/s1.jpg',
                    'title'=>'men1',
                    'desc'=>'Sed ut perspiciati1',
                    'actual_price'=>'$70.00',
                    'discount_price'=>'$60.00',                    
                    ),
                array(
                    'id'=>'166',
                    'src'=>'/images/men/sweatshirt/s2.jpg',
                    'title'=>'men1',
                    'desc'=>'Sed ut perspiciati1',
                    'actual_price'=>'$70.00',
                    'discount_price'=>'$60.00',    
                    ),
                array(
                    'id'=>'167',
                    'src'=>'/images/men/sweatshirt/s3.jpg',
                    'title'=>'men1',
                    'desc'=>'Sed ut perspiciati1',
                    'actual_price'=>'$70.00',
                    'discount_price'=>'$60.00',    
                    ),
                array(
                    'id'=>'168',
                    'src'=>'/images/men/sweatshirt/s4.jpg',
                    'title'=>'men1',
                    'desc'=>'Sed ut perspiciati1',
                    'actual_price'=>'$70.00',
                    'discount_price'=>'$60.00',    
                    ),
                array(
                    'id'=>'169',
                    'src'=>'/images/men/sweatshirt/s5.jpg',
                    'title'=>'men1',
                    'desc'=>'Sed ut perspiciati1',
                    'actual_price'=>'$70.00',
                    'discount_price'=>'$60.00',                    
                    ),
                array(
                    'id'=>'170',
                    'src'=>'/images/men/sweatshirt/s6.jpg',
                    'title'=>'men1',
                    'desc'=>'Sed ut perspiciati1',
                    'actual_price'=>'$70.00',
                    'discount_price'=>'$60.00',    
                    ),
                array(
                    'id'=>'171',
                    'src'=>'/images/men/sweatshirt/s7.jpg',
                    'title'=>'men1',
                    'desc'=>'Sed ut perspiciati1',
                    'actual_price'=>'$70.00',
                    'discount_price'=>'$60.00',    
                    ),
                array(
                    'id'=>'172',
                    'src'=>'/images/men/sweatshirt/s8.jpg',
                    'title'=>'men1',
                    'desc'=>'Sed ut perspiciati1',
                    'actual_price'=>'$70.00',
                    'discount_price'=>'$60.00',    
                    ),            
            ],
            'swimwear'=>[
                array(
                    'id'=>'173',
                    'src'=>'/images/men/swimwear/swim1.jpg',
                    'title'=>'men1',
                    'desc'=>'Sed ut perspiciati1',
                    'actual_price'=>'$70.00',
                    'discount_price'=>'$60.00',                    
                    ),
                array(
                    'id'=>'174',
                    'src'=>'/images/men/swimwear/swim2.jpg',
                    'title'=>'men1',
                    'desc'=>'Sed ut perspiciati1',
                    'actual_price'=>'$70.00',
                    'discount_price'=>'$60.00',    
                    ),
                array(
                    'id'=>'175',
                    'src'=>'/images/men/swimwear/swim3.jpg',
                    'title'=>'men1',
                    'desc'=>'Sed ut perspiciati1',
                    'actual_price'=>'$70.00',
                    'discount_price'=>'$60.00',    
                    ),
                array(
                    'id'=>'176',
                    'src'=>'/images/men/swimwear/swim4.jpg',
                    'title'=>'men1',
                    'desc'=>'Sed ut perspiciati1',
                    'actual_price'=>'$70.00',
                    'discount_price'=>'$60.00',    
                    ),
            ],
            'trouser'=>[
                array(
                    'id'=>'177',
                    'src'=>'/images/men/trouser/trouser1.jpg',
                    'title'=>'men1',
                    'desc'=>'Sed ut perspiciati1',
                    'actual_price'=>'$70.00',
                    'discount_price'=>'$60.00',                    
                    ),
                array(
                    'id'=>'178',
                    'src'=>'/images/men/trouser/trouser2.jpg',
                    'title'=>'men1',
                    'desc'=>'Sed ut perspiciati1',
                    'actual_price'=>'$70.00',
                    'discount_price'=>'$60.00',    
                    ),
                array(
                    'id'=>'179',
                    'src'=>'/images/men/trouser/trouser3.jpg',
                    'title'=>'men1',
                    'desc'=>'Sed ut perspiciati1',
                    'actual_price'=>'$70.00',
                    'discount_price'=>'$60.00',    
                    ),
                array(
                    'id'=>'180',
                    'src'=>'/images/men/trouser/trouser4.jpg',
                    'title'=>'men1',
                    'desc'=>'Sed ut perspiciati1',
                    'actual_price'=>'$70.00',
                    'discount_price'=>'$60.00',    
                    ),
            ],
            'tshirt'=>[
                array(
                    'id'=>'181',
                    'src'=>'/images/men/tshirt/t6.jpg',
                    'title'=>'men1',
                    'desc'=>'Sed ut perspiciati1',
                    'actual_price'=>'$70.00',
                    'discount_price'=>'$60.00',    
                    ),
                array(
                    'id'=>'182',
                    'src'=>'/images/men/tshirt/t7.jpg',
                    'title'=>'men1',
                    'desc'=>'Sed ut perspiciati1',
                    'actual_price'=>'$70.00',
                    'discount_price'=>'$60.00',    
                    ),
                array(
                    'id'=>'183',
                    'src'=>'/images/men/tshirt/t8.jpg',
                    'title'=>'men1',
                    'desc'=>'Sed ut perspiciati1',
                    'actual_price'=>'$70.00',
                    'discount_price'=>'$60.00',    
                    ),   
                array(
                    'id'=>'184',
                    'src'=>'/images/men/tshirt/t4.jpg',
                    'title'=>'men1',
                    'desc'=>'Sed ut perspiciati1',
                    'actual_price'=>'$70.00',
                    'discount_price'=>'$60.00',    
                    ),    
                array(
                    'id'=>'185',
                    'src'=>'/images/men/tshirt/t5.jpg',
                    'title'=>'men1',
                    'desc'=>'Sed ut perspiciati1',
                    'actual_price'=>'$70.00',
                    'discount_price'=>'$60.00',                    
                    ),  
                array(
                    'id'=>'186',
                    'src'=>'/images/men/tshirt/t1.jpg',
                    'title'=>'men1',
                    'desc'=>'Sed ut perspiciati1',
                    'actual_price'=>'$70.00',
                    'discount_price'=>'$60.00',                    
                    ),
                array(
                    'id'=>'187',
                    'src'=>'/images/men/tshirt/t2.jpg',
                    'title'=>'men1',
                    'desc'=>'Sed ut perspiciati1',
                    'actual_price'=>'$70.00',
                    'discount_price'=>'$60.00',    
                    ),
                array(
                    'id'=>'188',
                    'src'=>'/images/men/tshirt/t3.jpg',
                    'title'=>'men1',
                    'desc'=>'Sed ut perspiciati1',
                    'actual_price'=>'$70.00',
                    'discount_price'=>'$60.00',    
                    ),                                                                   
            ],
            'underwear'=>[
                array(
                    'id'=>'189',
                    'src'=>'/images/men/underwear/u1.jpg',
                    'title'=>'men1',
                    'desc'=>'Sed ut perspiciati1',
                    'actual_price'=>'$70.00',
                    'discount_price'=>'$60.00',                    
                    ),
                array(
                    'id'=>'190',
                    'src'=>'/images/men/underwear/u2.jpg',
                    'title'=>'men1',
                    'desc'=>'Sed ut perspiciati1',
                    'actual_price'=>'$70.00',
                    'discount_price'=>'$60.00',    
                    ),
                array(
                    'id'=>'191',
                    'src'=>'/images/men/underwear/u3.jpg',
                    'title'=>'men1',
                    'desc'=>'Sed ut perspiciati1',
                    'actual_price'=>'$70.00',
                    'discount_price'=>'$60.00',    
                    ),
                array(
                    'id'=>'192',
                    'src'=>'/images/men/underwear/u4.jpg',
                    'title'=>'men1',
                    'desc'=>'Sed ut perspiciati1',
                    'actual_price'=>'$70.00',
                    'discount_price'=>'$60.00',    
                    ),
            ],
            'vest'=>[
                array(
                    'id'=>'193',
                    'src'=>'/images/men/vest/v1.jpg',
                    'title'=>'men1',
                    'desc'=>'Sed ut perspiciati1',
                    'actual_price'=>'$70.00',
                    'discount_price'=>'$60.00',                    
                    ),
                array(
                    'id'=>'194',
                    'src'=>'/images/men/vest/v2.jpg',
                    'title'=>'men1',
                    'desc'=>'Sed ut perspiciati1',
                    'actual_price'=>'$70.00',
                    'discount_price'=>'$60.00',    
                    ),
                array(
                    'id'=>'195',
                    'src'=>'/images/men/vest/v3.jpg',
                    'title'=>'men1',
                    'desc'=>'Sed ut perspiciati1',
                    'actual_price'=>'$70.00',
                    'discount_price'=>'$60.00',    
                    ),
                array(
                    'id'=>'196',
                    'src'=>'/images/men/vest/v4.jpg',
                    'title'=>'men1',
                    'desc'=>'Sed ut perspiciati1',
                    'actual_price'=>'$70.00',
                    'discount_price'=>'$60.00',    
                    ),
            ],              
        ]
    ],

];
